# SMARTRANKING  API REQUESTS

## VARIABLES
@apiurl = http://localhost:3001


################## PLAYERS RELATED ##################
@playerId = 67945c8d0ebd8a00728ae7b5

### GET PLAYERS
GET {{apiurl}}/api/v1/players

### CREATE PLAYER
POST {{apiurl}}/api/v1/players
Content-Type: application/json

{
  "name": "Player Name 2",
  "email": "player2@example.com",
  "phoneNumber": "1234567892"
}

### GET PLAYER BY ID
GET {{apiurl}}/api/v1/players/{{playerId}}

### UPDATE PLAYER BY ID
PUT {{apiurl}}/api/v1/players/{{playerId}}
Content-Type: application/json

{
  "name": "Updated Player Name",
  "email": "updatedplayer@example.com",
  "phoneNumber": "0987654321"
}

### DELETE PLAYER BY ID
DELETE {{apiurl}}/api/v1/players/{{playerId}}

#####################################################



################## CATEGORIES RELATED ##################
@categoryId = 67945fa2b553f86f559ad0bc

### GET CATEGORIES
GET {{apiurl}}/api/v1/categories

### CREATE CATEGORY
POST {{apiurl}}/api/v1/categories
Content-Type: application/json

{
  "name": "Category Name",
  "description": "Category Description",
  "events":[{
    "name":"party"
  }]
}

### ASSIGN PLAYER TO CATEGORY
POST {{apiurl}}/api/v1/categories/{{categoryId}}/players/{{playerId}}
Content-Type: application/json

{

}

### GET CATEGORY BY ID
GET {{apiurl}}/api/v1/categories/{{categoryId}}

### UPDATE CATEGORY BY ID
PUT {{apiurl}}/api/v1/categories/{{categoryId}}
Content-Type: application/json

{
  "name": "Updated Category Name",
  "description": "Updated Category Description"
}

### DELETE CATEGORY BY ID
DELETE {{apiurl}}/api/v1/categories/{{categoryId}}

#####################################################


################## CHALLENGES RELATED ##################
@challengeId = 67946a48b553f86f559ad0c1
@player1Id = 67945c8d0ebd8a00728ae7b5
@player2Id = 67945c910ebd8a00728ae7b7

### CREATE CHALLENGE
POST {{apiurl}}/api/v1/challengers
Content-Type: application/json

{
  "challengeDate": "2026-03-20T15:00:00Z",
  "requester": { "_id": "{{player1Id}}" },
  "players": [
    { "_id": "{{player1Id}}" },
    { "_id": "{{player2Id}}" }
  ]
}

### GET ALL CHALLENGES
GET {{apiurl}}/api/v1/challengers

### GET CHALLENGES BY PLAYER
GET {{apiurl}}/api/v1/challengers?playerId={{player1Id}}

### GET CHALLENGE BY ID
GET {{apiurl}}/api/v1/challengers/{{challengeId}}

### UPDATE CHALLENGE (Status/Date)
PUT {{apiurl}}/api/v1/challengers/{{challengeId}}
Content-Type: application/json

{
  "status": "ACCEPTED"
}

### ASSIGN MATCH TO CHALLENGE (Result)
POST {{apiurl}}/api/v1/challengers/{{challengeId}}/match
Content-Type: application/json

{
  "def": { "_id": "{{player1Id}}" },
  "result": [
    { "set": "6-1" },
    { "set": "4-6" },
    { "set": "7-5" }
  ]
}

### DELETE CHALLENGE
DELETE {{apiurl}}/api/v1/challengers/{{challengeId}}

#####################################################
